"""Generate MEMORY.md per machine from frontmatter scope, and lint for drift.

This is the load-bearing mechanism of the design. MEMORY.md is the file both
agents append to constantly, so tracking it guarantees perpetual conflicts.
Generating it per machine removes that conflict class entirely.
"""
from pathlib import Path
from .frontmatter import parse, scope_of

# Which scopes each physical directory is expected to hold.
DIR_SCOPE = {
    "_shared": {"estate"},
    "_local": {"winpc", "macmini"},
    "_peer-local": {"winpc", "macmini"},
}

HEADER = (
    "<!-- GENERATED by memory_sync. Do not edit; do not commit. "
    "Regenerate with: memory-sync index -->\n\n"
)


def collect(root, machine):
    """Entries this machine should LOAD: scope == estate, or scope == machine.

    _peer-local is excluded by directory because it is the peer's local set:
    present on disk for backup and cross-review, never loaded (spec D2).
    """
    out = []
    for d in ("_shared", "_local"):
        base = Path(root) / d
        if not base.is_dir():
            continue
        default = "estate" if d == "_shared" else machine
        for f in sorted(base.glob("*.md")):
            if f.name == "MEMORY.md":
                continue
            meta, _ = parse(f.read_text(encoding="utf-8"))
            scope = scope_of(meta, default)
            if scope not in ("estate", machine):
                continue
            out.append({
                "path": "{}/{}".format(d, f.name),
                "dirname": d,
                "name": meta.get("name") or f.stem,
                "description": meta.get("description") or "",
                "scope": scope,
            })
    return out


def render(entries):
    lines = [HEADER]
    for e in sorted(entries, key=lambda x: x["name"]):
        lines.append("- [{n}]({p}) - {d}\n".format(
            n=e["name"], p=e["path"], d=e["description"]))
    return "".join(lines)


def lint(entries):
    """Flag files whose directory and declared scope disagree (spec O3).

    Scope is expressed in two places and they can drift. Frontmatter is
    authoritative for loading; this catches the disagreement by construction
    rather than leaving it to be noticed later.
    """
    problems = []
    seen = set()
    for e in entries:
        key = e["path"]
        if key in seen:
            continue
        seen.add(key)
        allowed = DIR_SCOPE.get(e["dirname"], set())
        if allowed and e["scope"] not in allowed:
            problems.append(
                "scope/dir disagreement: {p} is in {d} but declares scope: {s}".format(
                    p=e["name"], d=e["dirname"], s=e["scope"])
            )
    return sorted(problems)
